//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.11 at 02:39:34 PM EST 
//


package schemas.docbook;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the schemas.docbook package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: schemas.docbook
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Lineage }
     * 
     */
    public Lineage createLineage() {
        return new Lineage();
    }

    /**
     * Create an instance of {@link Inlinemediaobject }
     * 
     */
    public Inlinemediaobject createInlinemediaobject() {
        return new Inlinemediaobject();
    }

    /**
     * Create an instance of {@link Info }
     * 
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Remark }
     * 
     */
    public Remark createRemark() {
        return new Remark();
    }

    /**
     * Create an instance of {@link Superscript }
     * 
     */
    public Superscript createSuperscript() {
        return new Superscript();
    }

    /**
     * Create an instance of {@link Subscript }
     * 
     */
    public Subscript createSubscript() {
        return new Subscript();
    }

    /**
     * Create an instance of {@link Xref }
     * 
     */
    public Xref createXref() {
        return new Xref();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Olink }
     * 
     */
    public Olink createOlink() {
        return new Olink();
    }

    /**
     * Create an instance of {@link Anchor }
     * 
     */
    public Anchor createAnchor() {
        return new Anchor();
    }

    /**
     * Create an instance of {@link Biblioref }
     * 
     */
    public Biblioref createBiblioref() {
        return new Biblioref();
    }

    /**
     * Create an instance of {@link Alt }
     * 
     */
    public Alt createAlt() {
        return new Alt();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link Titleabbrev }
     * 
     */
    public Titleabbrev createTitleabbrev() {
        return new Titleabbrev();
    }

    /**
     * Create an instance of {@link Indexterm }
     * 
     */
    public Indexterm createIndexterm() {
        return new Indexterm();
    }

    /**
     * Create an instance of {@link Primary }
     * 
     */
    public Primary createPrimary() {
        return new Primary();
    }

    /**
     * Create an instance of {@link Abbrev }
     * 
     */
    public Abbrev createAbbrev() {
        return new Abbrev();
    }

    /**
     * Create an instance of {@link Phrase }
     * 
     */
    public Phrase createPhrase() {
        return new Phrase();
    }

    /**
     * Create an instance of {@link Acronym }
     * 
     */
    public Acronym createAcronym() {
        return new Acronym();
    }

    /**
     * Create an instance of {@link Replaceable }
     * 
     */
    public Replaceable createReplaceable() {
        return new Replaceable();
    }

    /**
     * Create an instance of {@link Co }
     * 
     */
    public Co createCo() {
        return new Co();
    }

    /**
     * Create an instance of {@link Trademark }
     * 
     */
    public Trademark createTrademark() {
        return new Trademark();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link Emphasis }
     * 
     */
    public Emphasis createEmphasis() {
        return new Emphasis();
    }

    /**
     * Create an instance of {@link Footnote }
     * 
     */
    public Footnote createFootnote() {
        return new Footnote();
    }

    /**
     * Create an instance of {@link Itemizedlist }
     * 
     */
    public Itemizedlist createItemizedlist() {
        return new Itemizedlist();
    }

    /**
     * Create an instance of {@link Orderedlist }
     * 
     */
    public Orderedlist createOrderedlist() {
        return new Orderedlist();
    }

    /**
     * Create an instance of {@link Procedure }
     * 
     */
    public Procedure createProcedure() {
        return new Procedure();
    }

    /**
     * Create an instance of {@link Simplelist }
     * 
     */
    public Simplelist createSimplelist() {
        return new Simplelist();
    }

    /**
     * Create an instance of {@link Member }
     * 
     */
    public Member createMember() {
        return new Member();
    }

    /**
     * Create an instance of {@link Footnoteref }
     * 
     */
    public Footnoteref createFootnoteref() {
        return new Footnoteref();
    }

    /**
     * Create an instance of {@link Foreignphrase }
     * 
     */
    public Foreignphrase createForeignphrase() {
        return new Foreignphrase();
    }

    /**
     * Create an instance of {@link Quote }
     * 
     */
    public Quote createQuote() {
        return new Quote();
    }

    /**
     * Create an instance of {@link Wordasword }
     * 
     */
    public Wordasword createWordasword() {
        return new Wordasword();
    }

    /**
     * Create an instance of {@link Firstterm }
     * 
     */
    public Firstterm createFirstterm() {
        return new Firstterm();
    }

    /**
     * Create an instance of {@link Glossterm }
     * 
     */
    public Glossterm createGlossterm() {
        return new Glossterm();
    }

    /**
     * Create an instance of {@link Coref }
     * 
     */
    public Coref createCoref() {
        return new Coref();
    }

    /**
     * Create an instance of {@link Productnumber }
     * 
     */
    public Productnumber createProductnumber() {
        return new Productnumber();
    }

    /**
     * Create an instance of {@link Productname }
     * 
     */
    public Productname createProductname() {
        return new Productname();
    }

    /**
     * Create an instance of {@link Database }
     * 
     */
    public Database createDatabase() {
        return new Database();
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link Hardware }
     * 
     */
    public Hardware createHardware() {
        return new Hardware();
    }

    /**
     * Create an instance of {@link Citation }
     * 
     */
    public Citation createCitation() {
        return new Citation();
    }

    /**
     * Create an instance of {@link Citerefentry }
     * 
     */
    public Citerefentry createCiterefentry() {
        return new Citerefentry();
    }

    /**
     * Create an instance of {@link Refentrytitle }
     * 
     */
    public Refentrytitle createRefentrytitle() {
        return new Refentrytitle();
    }

    /**
     * Create an instance of {@link Citetitle }
     * 
     */
    public Citetitle createCitetitle() {
        return new Citetitle();
    }

    /**
     * Create an instance of {@link Citebiblioid }
     * 
     */
    public Citebiblioid createCitebiblioid() {
        return new Citebiblioid();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Orgname }
     * 
     */
    public Orgname createOrgname() {
        return new Orgname();
    }

    /**
     * Create an instance of {@link Personname }
     * 
     */
    public Personname createPersonname() {
        return new Personname();
    }

    /**
     * Create an instance of {@link Honorific }
     * 
     */
    public Honorific createHonorific() {
        return new Honorific();
    }

    /**
     * Create an instance of {@link Firstname }
     * 
     */
    public Firstname createFirstname() {
        return new Firstname();
    }

    /**
     * Create an instance of {@link Surname }
     * 
     */
    public Surname createSurname() {
        return new Surname();
    }

    /**
     * Create an instance of {@link Othername }
     * 
     */
    public Othername createOthername() {
        return new Othername();
    }

    /**
     * Create an instance of {@link Personblurb }
     * 
     */
    public Personblurb createPersonblurb() {
        return new Personblurb();
    }

    /**
     * Create an instance of {@link Para }
     * 
     */
    public Para createPara() {
        return new Para();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Pob }
     * 
     */
    public Pob createPob() {
        return new Pob();
    }

    /**
     * Create an instance of {@link Street }
     * 
     */
    public Street createStreet() {
        return new Street();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link Postcode }
     * 
     */
    public Postcode createPostcode() {
        return new Postcode();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link Fax }
     * 
     */
    public Fax createFax() {
        return new Fax();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link Uri }
     * 
     */
    public Uri createUri() {
        return new Uri();
    }

    /**
     * Create an instance of {@link Otheraddr }
     * 
     */
    public Otheraddr createOtheraddr() {
        return new Otheraddr();
    }

    /**
     * Create an instance of {@link Affiliation }
     * 
     */
    public Affiliation createAffiliation() {
        return new Affiliation();
    }

    /**
     * Create an instance of {@link Shortaffil }
     * 
     */
    public Shortaffil createShortaffil() {
        return new Shortaffil();
    }

    /**
     * Create an instance of {@link Jobtitle }
     * 
     */
    public Jobtitle createJobtitle() {
        return new Jobtitle();
    }

    /**
     * Create an instance of {@link Orgdiv }
     * 
     */
    public Orgdiv createOrgdiv() {
        return new Orgdiv();
    }

    /**
     * Create an instance of {@link Org }
     * 
     */
    public Org createOrg() {
        return new Org();
    }

    /**
     * Create an instance of {@link Editor }
     * 
     */
    public Editor createEditor() {
        return new Editor();
    }

    /**
     * Create an instance of {@link Contrib }
     * 
     */
    public Contrib createContrib() {
        return new Contrib();
    }

    /**
     * Create an instance of {@link Package }
     * 
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Termdef }
     * 
     */
    public Termdef createTermdef() {
        return new Termdef();
    }

    /**
     * Create an instance of {@link Nonterminal }
     * 
     */
    public Nonterminal createNonterminal() {
        return new Nonterminal();
    }

    /**
     * Create an instance of {@link Systemitem }
     * 
     */
    public Systemitem createSystemitem() {
        return new Systemitem();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link Optional }
     * 
     */
    public Optional createOptional() {
        return new Optional();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Inlineequation }
     * 
     */
    public Inlineequation createInlineequation() {
        return new Inlineequation();
    }

    /**
     * Create an instance of {@link Mathphrase }
     * 
     */
    public Mathphrase createMathphrase() {
        return new Mathphrase();
    }

    /**
     * Create an instance of {@link Tag }
     * 
     */
    public Tag createTag() {
        return new Tag();
    }

    /**
     * Create an instance of {@link Markup }
     * 
     */
    public Markup createMarkup() {
        return new Markup();
    }

    /**
     * Create an instance of {@link Token }
     * 
     */
    public Token createToken() {
        return new Token();
    }

    /**
     * Create an instance of {@link Symbol }
     * 
     */
    public Symbol createSymbol() {
        return new Symbol();
    }

    /**
     * Create an instance of {@link Literal }
     * 
     */
    public Literal createLiteral() {
        return new Literal();
    }

    /**
     * Create an instance of {@link Code }
     * 
     */
    public Code createCode() {
        return new Code();
    }

    /**
     * Create an instance of {@link Function }
     * 
     */
    public Function createFunction() {
        return new Function();
    }

    /**
     * Create an instance of {@link Varname }
     * 
     */
    public Varname createVarname() {
        return new Varname();
    }

    /**
     * Create an instance of {@link Returnvalue }
     * 
     */
    public Returnvalue createReturnvalue() {
        return new Returnvalue();
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createType() {
        return new Type();
    }

    /**
     * Create an instance of {@link Classname }
     * 
     */
    public Classname createClassname() {
        return new Classname();
    }

    /**
     * Create an instance of {@link Exceptionname }
     * 
     */
    public Exceptionname createExceptionname() {
        return new Exceptionname();
    }

    /**
     * Create an instance of {@link Interfacename }
     * 
     */
    public Interfacename createInterfacename() {
        return new Interfacename();
    }

    /**
     * Create an instance of {@link Methodname }
     * 
     */
    public Methodname createMethodname() {
        return new Methodname();
    }

    /**
     * Create an instance of {@link Modifier }
     * 
     */
    public Modifier createModifier() {
        return new Modifier();
    }

    /**
     * Create an instance of {@link Initializer }
     * 
     */
    public Initializer createInitializer() {
        return new Initializer();
    }

    /**
     * Create an instance of {@link Ooclass }
     * 
     */
    public Ooclass createOoclass() {
        return new Ooclass();
    }

    /**
     * Create an instance of {@link Ooexception }
     * 
     */
    public Ooexception createOoexception() {
        return new Ooexception();
    }

    /**
     * Create an instance of {@link Oointerface }
     * 
     */
    public Oointerface createOointerface() {
        return new Oointerface();
    }

    /**
     * Create an instance of {@link Constant }
     * 
     */
    public Constant createConstant() {
        return new Constant();
    }

    /**
     * Create an instance of {@link Guiicon }
     * 
     */
    public Guiicon createGuiicon() {
        return new Guiicon();
    }

    /**
     * Create an instance of {@link Accel }
     * 
     */
    public Accel createAccel() {
        return new Accel();
    }

    /**
     * Create an instance of {@link Guibutton }
     * 
     */
    public Guibutton createGuibutton() {
        return new Guibutton();
    }

    /**
     * Create an instance of {@link Guimenuitem }
     * 
     */
    public Guimenuitem createGuimenuitem() {
        return new Guimenuitem();
    }

    /**
     * Create an instance of {@link Guimenu }
     * 
     */
    public Guimenu createGuimenu() {
        return new Guimenu();
    }

    /**
     * Create an instance of {@link Guisubmenu }
     * 
     */
    public Guisubmenu createGuisubmenu() {
        return new Guisubmenu();
    }

    /**
     * Create an instance of {@link Guilabel }
     * 
     */
    public Guilabel createGuilabel() {
        return new Guilabel();
    }

    /**
     * Create an instance of {@link Menuchoice }
     * 
     */
    public Menuchoice createMenuchoice() {
        return new Menuchoice();
    }

    /**
     * Create an instance of {@link Shortcut }
     * 
     */
    public Shortcut createShortcut() {
        return new Shortcut();
    }

    /**
     * Create an instance of {@link Keycap }
     * 
     */
    public Keycap createKeycap() {
        return new Keycap();
    }

    /**
     * Create an instance of {@link Keycombo }
     * 
     */
    public Keycombo createKeycombo() {
        return new Keycombo();
    }

    /**
     * Create an instance of {@link Keysym }
     * 
     */
    public Keysym createKeysym() {
        return new Keysym();
    }

    /**
     * Create an instance of {@link Mousebutton }
     * 
     */
    public Mousebutton createMousebutton() {
        return new Mousebutton();
    }

    /**
     * Create an instance of {@link Keycode }
     * 
     */
    public Keycode createKeycode() {
        return new Keycode();
    }

    /**
     * Create an instance of {@link Prompt }
     * 
     */
    public Prompt createPrompt() {
        return new Prompt();
    }

    /**
     * Create an instance of {@link Envar }
     * 
     */
    public Envar createEnvar() {
        return new Envar();
    }

    /**
     * Create an instance of {@link Filename }
     * 
     */
    public Filename createFilename() {
        return new Filename();
    }

    /**
     * Create an instance of {@link Command }
     * 
     */
    public Command createCommand() {
        return new Command();
    }

    /**
     * Create an instance of {@link Computeroutput }
     * 
     */
    public Computeroutput createComputeroutput() {
        return new Computeroutput();
    }

    /**
     * Create an instance of {@link Userinput }
     * 
     */
    public Userinput createUserinput() {
        return new Userinput();
    }

    /**
     * Create an instance of {@link Errorcode }
     * 
     */
    public Errorcode createErrorcode() {
        return new Errorcode();
    }

    /**
     * Create an instance of {@link Errortext }
     * 
     */
    public Errortext createErrortext() {
        return new Errortext();
    }

    /**
     * Create an instance of {@link Errorname }
     * 
     */
    public Errorname createErrorname() {
        return new Errorname();
    }

    /**
     * Create an instance of {@link Errortype }
     * 
     */
    public Errortype createErrortype() {
        return new Errortype();
    }

    /**
     * Create an instance of {@link Variablelist }
     * 
     */
    public Variablelist createVariablelist() {
        return new Variablelist();
    }

    /**
     * Create an instance of {@link Segmentedlist }
     * 
     */
    public Segmentedlist createSegmentedlist() {
        return new Segmentedlist();
    }

    /**
     * Create an instance of {@link Segtitle }
     * 
     */
    public Segtitle createSegtitle() {
        return new Segtitle();
    }

    /**
     * Create an instance of {@link Seglistitem }
     * 
     */
    public Seglistitem createSeglistitem() {
        return new Seglistitem();
    }

    /**
     * Create an instance of {@link Seg }
     * 
     */
    public Seg createSeg() {
        return new Seg();
    }

    /**
     * Create an instance of {@link Glosslist }
     * 
     */
    public Glosslist createGlosslist() {
        return new Glosslist();
    }

    /**
     * Create an instance of {@link Bibliolist }
     * 
     */
    public Bibliolist createBibliolist() {
        return new Bibliolist();
    }

    /**
     * Create an instance of {@link Calloutlist }
     * 
     */
    public Calloutlist createCalloutlist() {
        return new Calloutlist();
    }

    /**
     * Create an instance of {@link Qandaset }
     * 
     */
    public Qandaset createQandaset() {
        return new Qandaset();
    }

    /**
     * Create an instance of {@link Example }
     * 
     */
    public Example createExample() {
        return new Example();
    }

    /**
     * Create an instance of {@link Figure }
     * 
     */
    public Figure createFigure() {
        return new Figure();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Caption }
     * 
     */
    public Caption createCaption() {
        return new Caption();
    }

    /**
     * Create an instance of {@link Caution }
     * 
     */
    public Caution createCaution() {
        return new Caution();
    }

    /**
     * Create an instance of {@link Equation }
     * 
     */
    public Equation createEquation() {
        return new Equation();
    }

    /**
     * Create an instance of {@link Mediaobject }
     * 
     */
    public Mediaobject createMediaobject() {
        return new Mediaobject();
    }

    /**
     * Create an instance of {@link Videoobject }
     * 
     */
    public Videoobject createVideoobject() {
        return new Videoobject();
    }

    /**
     * Create an instance of {@link Videodata }
     * 
     */
    public Videodata createVideodata() {
        return new Videodata();
    }

    /**
     * Create an instance of {@link Audioobject }
     * 
     */
    public Audioobject createAudioobject() {
        return new Audioobject();
    }

    /**
     * Create an instance of {@link Audiodata }
     * 
     */
    public Audiodata createAudiodata() {
        return new Audiodata();
    }

    /**
     * Create an instance of {@link Imageobject }
     * 
     */
    public Imageobject createImageobject() {
        return new Imageobject();
    }

    /**
     * Create an instance of {@link Imagedata }
     * 
     */
    public Imagedata createImagedata() {
        return new Imagedata();
    }

    /**
     * Create an instance of {@link Textobject }
     * 
     */
    public Textobject createTextobject() {
        return new Textobject();
    }

    /**
     * Create an instance of {@link Informalexample }
     * 
     */
    public Informalexample createInformalexample() {
        return new Informalexample();
    }

    /**
     * Create an instance of {@link Informalfigure }
     * 
     */
    public Informalfigure createInformalfigure() {
        return new Informalfigure();
    }

    /**
     * Create an instance of {@link Informaltable }
     * 
     */
    public Informaltable createInformaltable() {
        return new Informaltable();
    }

    /**
     * Create an instance of {@link Colgroup }
     * 
     */
    public Colgroup createColgroup() {
        return new Colgroup();
    }

    /**
     * Create an instance of {@link Col }
     * 
     */
    public Col createCol() {
        return new Col();
    }

    /**
     * Create an instance of {@link Thead }
     * 
     */
    public Thead createThead() {
        return new Thead();
    }

    /**
     * Create an instance of {@link Colspec }
     * 
     */
    public Colspec createColspec() {
        return new Colspec();
    }

    /**
     * Create an instance of {@link Tr }
     * 
     */
    public Tr createTr() {
        return new Tr();
    }

    /**
     * Create an instance of {@link Th }
     * 
     */
    public Th createTh() {
        return new Th();
    }

    /**
     * Create an instance of {@link Informalequation }
     * 
     */
    public Informalequation createInformalequation() {
        return new Informalequation();
    }

    /**
     * Create an instance of {@link Sidebar }
     * 
     */
    public Sidebar createSidebar() {
        return new Sidebar();
    }

    /**
     * Create an instance of {@link Blockquote }
     * 
     */
    public Blockquote createBlockquote() {
        return new Blockquote();
    }

    /**
     * Create an instance of {@link Attribution }
     * 
     */
    public Attribution createAttribution() {
        return new Attribution();
    }

    /**
     * Create an instance of {@link Epigraph }
     * 
     */
    public Epigraph createEpigraph() {
        return new Epigraph();
    }

    /**
     * Create an instance of {@link Formalpara }
     * 
     */
    public Formalpara createFormalpara() {
        return new Formalpara();
    }

    /**
     * Create an instance of {@link Simpara }
     * 
     */
    public Simpara createSimpara() {
        return new Simpara();
    }

    /**
     * Create an instance of {@link Literallayout }
     * 
     */
    public Literallayout createLiterallayout() {
        return new Literallayout();
    }

    /**
     * Create an instance of {@link Lineannotation }
     * 
     */
    public Lineannotation createLineannotation() {
        return new Lineannotation();
    }

    /**
     * Create an instance of {@link Screenshot }
     * 
     */
    public Screenshot createScreenshot() {
        return new Screenshot();
    }

    /**
     * Create an instance of {@link Subtitle }
     * 
     */
    public Subtitle createSubtitle() {
        return new Subtitle();
    }

    /**
     * Create an instance of {@link Task }
     * 
     */
    public Task createTask() {
        return new Task();
    }

    /**
     * Create an instance of {@link Tasksummary }
     * 
     */
    public Tasksummary createTasksummary() {
        return new Tasksummary();
    }

    /**
     * Create an instance of {@link Productionset }
     * 
     */
    public Productionset createProductionset() {
        return new Productionset();
    }

    /**
     * Create an instance of {@link Production }
     * 
     */
    public Production createProduction() {
        return new Production();
    }

    /**
     * Create an instance of {@link Lhs }
     * 
     */
    public Lhs createLhs() {
        return new Lhs();
    }

    /**
     * Create an instance of {@link Rhs }
     * 
     */
    public Rhs createRhs() {
        return new Rhs();
    }

    /**
     * Create an instance of {@link Sbr }
     * 
     */
    public Sbr createSbr() {
        return new Sbr();
    }

    /**
     * Create an instance of {@link Constraint }
     * 
     */
    public Constraint createConstraint() {
        return new Constraint();
    }

    /**
     * Create an instance of {@link Productionrecap }
     * 
     */
    public Productionrecap createProductionrecap() {
        return new Productionrecap();
    }

    /**
     * Create an instance of {@link Constraintdef }
     * 
     */
    public Constraintdef createConstraintdef() {
        return new Constraintdef();
    }

    /**
     * Create an instance of {@link Msgset }
     * 
     */
    public Msgset createMsgset() {
        return new Msgset();
    }

    /**
     * Create an instance of {@link Simplemsgentry }
     * 
     */
    public Simplemsgentry createSimplemsgentry() {
        return new Simplemsgentry();
    }

    /**
     * Create an instance of {@link Msgtext }
     * 
     */
    public Msgtext createMsgtext() {
        return new Msgtext();
    }

    /**
     * Create an instance of {@link Screen }
     * 
     */
    public Screen createScreen() {
        return new Screen();
    }

    /**
     * Create an instance of {@link Programlistingco }
     * 
     */
    public Programlistingco createProgramlistingco() {
        return new Programlistingco();
    }

    /**
     * Create an instance of {@link Areaspec }
     * 
     */
    public Areaspec createAreaspec() {
        return new Areaspec();
    }

    /**
     * Create an instance of {@link Area }
     * 
     */
    public Area createArea() {
        return new Area();
    }

    /**
     * Create an instance of {@link Areaset }
     * 
     */
    public Areaset createAreaset() {
        return new Areaset();
    }

    /**
     * Create an instance of {@link Programlisting }
     * 
     */
    public Programlisting createProgramlisting() {
        return new Programlisting();
    }

    /**
     * Create an instance of {@link Screenco }
     * 
     */
    public Screenco createScreenco() {
        return new Screenco();
    }

    /**
     * Create an instance of {@link Synopsis }
     * 
     */
    public Synopsis createSynopsis() {
        return new Synopsis();
    }

    /**
     * Create an instance of {@link Bridgehead }
     * 
     */
    public Bridgehead createBridgehead() {
        return new Bridgehead();
    }

    /**
     * Create an instance of {@link Revhistory }
     * 
     */
    public Revhistory createRevhistory() {
        return new Revhistory();
    }

    /**
     * Create an instance of {@link Revision }
     * 
     */
    public Revision createRevision() {
        return new Revision();
    }

    /**
     * Create an instance of {@link Revnumber }
     * 
     */
    public Revnumber createRevnumber() {
        return new Revnumber();
    }

    /**
     * Create an instance of {@link Authorinitials }
     * 
     */
    public Authorinitials createAuthorinitials() {
        return new Authorinitials();
    }

    /**
     * Create an instance of {@link Revdescription }
     * 
     */
    public Revdescription createRevdescription() {
        return new Revdescription();
    }

    /**
     * Create an instance of {@link Funcsynopsis }
     * 
     */
    public Funcsynopsis createFuncsynopsis() {
        return new Funcsynopsis();
    }

    /**
     * Create an instance of {@link Funcsynopsisinfo }
     * 
     */
    public Funcsynopsisinfo createFuncsynopsisinfo() {
        return new Funcsynopsisinfo();
    }

    /**
     * Create an instance of {@link Funcprototype }
     * 
     */
    public Funcprototype createFuncprototype() {
        return new Funcprototype();
    }

    /**
     * Create an instance of {@link Funcdef }
     * 
     */
    public Funcdef createFuncdef() {
        return new Funcdef();
    }

    /**
     * Create an instance of {@link Void }
     * 
     */
    public Void createVoid() {
        return new Void();
    }

    /**
     * Create an instance of {@link Varargs }
     * 
     */
    public Varargs createVarargs() {
        return new Varargs();
    }

    /**
     * Create an instance of {@link Paramdef }
     * 
     */
    public Paramdef createParamdef() {
        return new Paramdef();
    }

    /**
     * Create an instance of {@link Funcparams }
     * 
     */
    public Funcparams createFuncparams() {
        return new Funcparams();
    }

    /**
     * Create an instance of {@link Classsynopsis }
     * 
     */
    public Classsynopsis createClasssynopsis() {
        return new Classsynopsis();
    }

    /**
     * Create an instance of {@link Classsynopsisinfo }
     * 
     */
    public Classsynopsisinfo createClasssynopsisinfo() {
        return new Classsynopsisinfo();
    }

    /**
     * Create an instance of {@link Methodsynopsis }
     * 
     */
    public Methodsynopsis createMethodsynopsis() {
        return new Methodsynopsis();
    }

    /**
     * Create an instance of {@link Methodparam }
     * 
     */
    public Methodparam createMethodparam() {
        return new Methodparam();
    }

    /**
     * Create an instance of {@link Constructorsynopsis }
     * 
     */
    public Constructorsynopsis createConstructorsynopsis() {
        return new Constructorsynopsis();
    }

    /**
     * Create an instance of {@link Destructorsynopsis }
     * 
     */
    public Destructorsynopsis createDestructorsynopsis() {
        return new Destructorsynopsis();
    }

    /**
     * Create an instance of {@link Fieldsynopsis }
     * 
     */
    public Fieldsynopsis createFieldsynopsis() {
        return new Fieldsynopsis();
    }

    /**
     * Create an instance of {@link Cmdsynopsis }
     * 
     */
    public Cmdsynopsis createCmdsynopsis() {
        return new Cmdsynopsis();
    }

    /**
     * Create an instance of {@link Arg }
     * 
     */
    public Arg createArg() {
        return new Arg();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Synopfragmentref }
     * 
     */
    public Synopfragmentref createSynopfragmentref() {
        return new Synopfragmentref();
    }

    /**
     * Create an instance of {@link Synopfragment }
     * 
     */
    public Synopfragment createSynopfragment() {
        return new Synopfragment();
    }

    /**
     * Create an instance of {@link Important }
     * 
     */
    public Important createImportant() {
        return new Important();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link Tip }
     * 
     */
    public Tip createTip() {
        return new Tip();
    }

    /**
     * Create an instance of {@link Warning }
     * 
     */
    public Warning createWarning() {
        return new Warning();
    }

    /**
     * Create an instance of {@link Revremark }
     * 
     */
    public Revremark createRevremark() {
        return new Revremark();
    }

    /**
     * Create an instance of {@link Msgexplan }
     * 
     */
    public Msgexplan createMsgexplan() {
        return new Msgexplan();
    }

    /**
     * Create an instance of {@link Msgentry }
     * 
     */
    public Msgentry createMsgentry() {
        return new Msgentry();
    }

    /**
     * Create an instance of {@link Msg }
     * 
     */
    public Msg createMsg() {
        return new Msg();
    }

    /**
     * Create an instance of {@link Msgmain }
     * 
     */
    public Msgmain createMsgmain() {
        return new Msgmain();
    }

    /**
     * Create an instance of {@link Msgsub }
     * 
     */
    public Msgsub createMsgsub() {
        return new Msgsub();
    }

    /**
     * Create an instance of {@link Msgrel }
     * 
     */
    public Msgrel createMsgrel() {
        return new Msgrel();
    }

    /**
     * Create an instance of {@link Msginfo }
     * 
     */
    public Msginfo createMsginfo() {
        return new Msginfo();
    }

    /**
     * Create an instance of {@link Msglevel }
     * 
     */
    public Msglevel createMsglevel() {
        return new Msglevel();
    }

    /**
     * Create an instance of {@link Msgorig }
     * 
     */
    public Msgorig createMsgorig() {
        return new Msgorig();
    }

    /**
     * Create an instance of {@link Msgaud }
     * 
     */
    public Msgaud createMsgaud() {
        return new Msgaud();
    }

    /**
     * Create an instance of {@link Taskprerequisites }
     * 
     */
    public Taskprerequisites createTaskprerequisites() {
        return new Taskprerequisites();
    }

    /**
     * Create an instance of {@link Taskrelated }
     * 
     */
    public Taskrelated createTaskrelated() {
        return new Taskrelated();
    }

    /**
     * Create an instance of {@link Td }
     * 
     */
    public Td createTd() {
        return new Td();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link Entrytbl }
     * 
     */
    public Entrytbl createEntrytbl() {
        return new Entrytbl();
    }

    /**
     * Create an instance of {@link Spanspec }
     * 
     */
    public Spanspec createSpanspec() {
        return new Spanspec();
    }

    /**
     * Create an instance of {@link Tbody }
     * 
     */
    public Tbody createTbody() {
        return new Tbody();
    }

    /**
     * Create an instance of {@link Tfoot }
     * 
     */
    public Tfoot createTfoot() {
        return new Tfoot();
    }

    /**
     * Create an instance of {@link Tgroup }
     * 
     */
    public Tgroup createTgroup() {
        return new Tgroup();
    }

    /**
     * Create an instance of {@link Textdata }
     * 
     */
    public Textdata createTextdata() {
        return new Textdata();
    }

    /**
     * Create an instance of {@link Imageobjectco }
     * 
     */
    public Imageobjectco createImageobjectco() {
        return new Imageobjectco();
    }

    /**
     * Create an instance of {@link Qandaentry }
     * 
     */
    public Qandaentry createQandaentry() {
        return new Qandaentry();
    }

    /**
     * Create an instance of {@link Question }
     * 
     */
    public Question createQuestion() {
        return new Question();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link Answer }
     * 
     */
    public Answer createAnswer() {
        return new Answer();
    }

    /**
     * Create an instance of {@link Qandadiv }
     * 
     */
    public Qandadiv createQandadiv() {
        return new Qandadiv();
    }

    /**
     * Create an instance of {@link Callout }
     * 
     */
    public Callout createCallout() {
        return new Callout();
    }

    /**
     * Create an instance of {@link Biblioentry }
     * 
     */
    public Biblioentry createBiblioentry() {
        return new Biblioentry();
    }

    /**
     * Create an instance of {@link Abstract }
     * 
     */
    public Abstract createAbstract() {
        return new Abstract();
    }

    /**
     * Create an instance of {@link Artpagenums }
     * 
     */
    public Artpagenums createArtpagenums() {
        return new Artpagenums();
    }

    /**
     * Create an instance of {@link Authorgroup }
     * 
     */
    public Authorgroup createAuthorgroup() {
        return new Authorgroup();
    }

    /**
     * Create an instance of {@link Othercredit }
     * 
     */
    public Othercredit createOthercredit() {
        return new Othercredit();
    }

    /**
     * Create an instance of {@link Bibliocoverage }
     * 
     */
    public Bibliocoverage createBibliocoverage() {
        return new Bibliocoverage();
    }

    /**
     * Create an instance of {@link Biblioid }
     * 
     */
    public Biblioid createBiblioid() {
        return new Biblioid();
    }

    /**
     * Create an instance of {@link Bibliosource }
     * 
     */
    public Bibliosource createBibliosource() {
        return new Bibliosource();
    }

    /**
     * Create an instance of {@link Collab }
     * 
     */
    public Collab createCollab() {
        return new Collab();
    }

    /**
     * Create an instance of {@link Confgroup }
     * 
     */
    public Confgroup createConfgroup() {
        return new Confgroup();
    }

    /**
     * Create an instance of {@link Confdates }
     * 
     */
    public Confdates createConfdates() {
        return new Confdates();
    }

    /**
     * Create an instance of {@link Conftitle }
     * 
     */
    public Conftitle createConftitle() {
        return new Conftitle();
    }

    /**
     * Create an instance of {@link Confnum }
     * 
     */
    public Confnum createConfnum() {
        return new Confnum();
    }

    /**
     * Create an instance of {@link Confsponsor }
     * 
     */
    public Confsponsor createConfsponsor() {
        return new Confsponsor();
    }

    /**
     * Create an instance of {@link Contractsponsor }
     * 
     */
    public Contractsponsor createContractsponsor() {
        return new Contractsponsor();
    }

    /**
     * Create an instance of {@link Contractnum }
     * 
     */
    public Contractnum createContractnum() {
        return new Contractnum();
    }

    /**
     * Create an instance of {@link Copyright }
     * 
     */
    public Copyright createCopyright() {
        return new Copyright();
    }

    /**
     * Create an instance of {@link Year }
     * 
     */
    public Year createYear() {
        return new Year();
    }

    /**
     * Create an instance of {@link Holder }
     * 
     */
    public Holder createHolder() {
        return new Holder();
    }

    /**
     * Create an instance of {@link Cover }
     * 
     */
    public Cover createCover() {
        return new Cover();
    }

    /**
     * Create an instance of {@link Edition }
     * 
     */
    public Edition createEdition() {
        return new Edition();
    }

    /**
     * Create an instance of {@link Issuenum }
     * 
     */
    public Issuenum createIssuenum() {
        return new Issuenum();
    }

    /**
     * Create an instance of {@link Keywordset }
     * 
     */
    public Keywordset createKeywordset() {
        return new Keywordset();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link Legalnotice }
     * 
     */
    public Legalnotice createLegalnotice() {
        return new Legalnotice();
    }

    /**
     * Create an instance of {@link Pagenums }
     * 
     */
    public Pagenums createPagenums() {
        return new Pagenums();
    }

    /**
     * Create an instance of {@link Printhistory }
     * 
     */
    public Printhistory createPrinthistory() {
        return new Printhistory();
    }

    /**
     * Create an instance of {@link Pubdate }
     * 
     */
    public Pubdate createPubdate() {
        return new Pubdate();
    }

    /**
     * Create an instance of {@link Publisher }
     * 
     */
    public Publisher createPublisher() {
        return new Publisher();
    }

    /**
     * Create an instance of {@link Publishername }
     * 
     */
    public Publishername createPublishername() {
        return new Publishername();
    }

    /**
     * Create an instance of {@link Releaseinfo }
     * 
     */
    public Releaseinfo createReleaseinfo() {
        return new Releaseinfo();
    }

    /**
     * Create an instance of {@link Seriesvolnums }
     * 
     */
    public Seriesvolnums createSeriesvolnums() {
        return new Seriesvolnums();
    }

    /**
     * Create an instance of {@link Subjectset }
     * 
     */
    public Subjectset createSubjectset() {
        return new Subjectset();
    }

    /**
     * Create an instance of {@link Subject }
     * 
     */
    public Subject createSubject() {
        return new Subject();
    }

    /**
     * Create an instance of {@link Subjectterm }
     * 
     */
    public Subjectterm createSubjectterm() {
        return new Subjectterm();
    }

    /**
     * Create an instance of {@link Volumenum }
     * 
     */
    public Volumenum createVolumenum() {
        return new Volumenum();
    }

    /**
     * Create an instance of {@link Extendedlink }
     * 
     */
    public Extendedlink createExtendedlink() {
        return new Extendedlink();
    }

    /**
     * Create an instance of {@link Locator }
     * 
     */
    public Locator createLocator() {
        return new Locator();
    }

    /**
     * Create an instance of {@link Arc }
     * 
     */
    public Arc createArc() {
        return new Arc();
    }

    /**
     * Create an instance of {@link Bibliomisc }
     * 
     */
    public Bibliomisc createBibliomisc() {
        return new Bibliomisc();
    }

    /**
     * Create an instance of {@link Bibliomset }
     * 
     */
    public Bibliomset createBibliomset() {
        return new Bibliomset();
    }

    /**
     * Create an instance of {@link Bibliorelation }
     * 
     */
    public Bibliorelation createBibliorelation() {
        return new Bibliorelation();
    }

    /**
     * Create an instance of {@link Biblioset }
     * 
     */
    public Biblioset createBiblioset() {
        return new Biblioset();
    }

    /**
     * Create an instance of {@link Itermset }
     * 
     */
    public Itermset createItermset() {
        return new Itermset();
    }

    /**
     * Create an instance of {@link Bibliomixed }
     * 
     */
    public Bibliomixed createBibliomixed() {
        return new Bibliomixed();
    }

    /**
     * Create an instance of {@link Glossentry }
     * 
     */
    public Glossentry createGlossentry() {
        return new Glossentry();
    }

    /**
     * Create an instance of {@link Glossdef }
     * 
     */
    public Glossdef createGlossdef() {
        return new Glossdef();
    }

    /**
     * Create an instance of {@link Glossseealso }
     * 
     */
    public Glossseealso createGlossseealso() {
        return new Glossseealso();
    }

    /**
     * Create an instance of {@link Glosssee }
     * 
     */
    public Glosssee createGlosssee() {
        return new Glosssee();
    }

    /**
     * Create an instance of {@link Varlistentry }
     * 
     */
    public Varlistentry createVarlistentry() {
        return new Varlistentry();
    }

    /**
     * Create an instance of {@link Term }
     * 
     */
    public Term createTerm() {
        return new Term();
    }

    /**
     * Create an instance of {@link Listitem }
     * 
     */
    public Listitem createListitem() {
        return new Listitem();
    }

    /**
     * Create an instance of {@link Manvolnum }
     * 
     */
    public Manvolnum createManvolnum() {
        return new Manvolnum();
    }

    /**
     * Create an instance of {@link Step }
     * 
     */
    public Step createStep() {
        return new Step();
    }

    /**
     * Create an instance of {@link Substeps }
     * 
     */
    public Substeps createSubsteps() {
        return new Substeps();
    }

    /**
     * Create an instance of {@link Stepalternatives }
     * 
     */
    public Stepalternatives createStepalternatives() {
        return new Stepalternatives();
    }

    /**
     * Create an instance of {@link Secondary }
     * 
     */
    public Secondary createSecondary() {
        return new Secondary();
    }

    /**
     * Create an instance of {@link Tertiary }
     * 
     */
    public Tertiary createTertiary() {
        return new Tertiary();
    }

    /**
     * Create an instance of {@link Seealso }
     * 
     */
    public Seealso createSeealso() {
        return new Seealso();
    }

    /**
     * Create an instance of {@link See }
     * 
     */
    public See createSee() {
        return new See();
    }

    /**
     * Create an instance of {@link Refclass }
     * 
     */
    public Refclass createRefclass() {
        return new Refclass();
    }

    /**
     * Create an instance of {@link Seealsoie }
     * 
     */
    public Seealsoie createSeealsoie() {
        return new Seealsoie();
    }

    /**
     * Create an instance of {@link Appendix }
     * 
     */
    public Appendix createAppendix() {
        return new Appendix();
    }

    /**
     * Create an instance of {@link Glossary }
     * 
     */
    public Glossary createGlossary() {
        return new Glossary();
    }

    /**
     * Create an instance of {@link Glossdiv }
     * 
     */
    public Glossdiv createGlossdiv() {
        return new Glossdiv();
    }

    /**
     * Create an instance of {@link Bibliography }
     * 
     */
    public Bibliography createBibliography() {
        return new Bibliography();
    }

    /**
     * Create an instance of {@link Bibliodiv }
     * 
     */
    public Bibliodiv createBibliodiv() {
        return new Bibliodiv();
    }

    /**
     * Create an instance of {@link Index }
     * 
     */
    public Index createIndex() {
        return new Index();
    }

    /**
     * Create an instance of {@link Indexentry }
     * 
     */
    public Indexentry createIndexentry() {
        return new Indexentry();
    }

    /**
     * Create an instance of {@link Primaryie }
     * 
     */
    public Primaryie createPrimaryie() {
        return new Primaryie();
    }

    /**
     * Create an instance of {@link Seeie }
     * 
     */
    public Seeie createSeeie() {
        return new Seeie();
    }

    /**
     * Create an instance of {@link Secondaryie }
     * 
     */
    public Secondaryie createSecondaryie() {
        return new Secondaryie();
    }

    /**
     * Create an instance of {@link Tertiaryie }
     * 
     */
    public Tertiaryie createTertiaryie() {
        return new Tertiaryie();
    }

    /**
     * Create an instance of {@link Indexdiv }
     * 
     */
    public Indexdiv createIndexdiv() {
        return new Indexdiv();
    }

    /**
     * Create an instance of {@link Toc }
     * 
     */
    public Toc createToc() {
        return new Toc();
    }

    /**
     * Create an instance of {@link Tocdiv }
     * 
     */
    public Tocdiv createTocdiv() {
        return new Tocdiv();
    }

    /**
     * Create an instance of {@link Tocentry }
     * 
     */
    public Tocentry createTocentry() {
        return new Tocentry();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Refentry }
     * 
     */
    public Refentry createRefentry() {
        return new Refentry();
    }

    /**
     * Create an instance of {@link Refmeta }
     * 
     */
    public Refmeta createRefmeta() {
        return new Refmeta();
    }

    /**
     * Create an instance of {@link Refmiscinfo }
     * 
     */
    public Refmiscinfo createRefmiscinfo() {
        return new Refmiscinfo();
    }

    /**
     * Create an instance of {@link Refnamediv }
     * 
     */
    public Refnamediv createRefnamediv() {
        return new Refnamediv();
    }

    /**
     * Create an instance of {@link Refdescriptor }
     * 
     */
    public Refdescriptor createRefdescriptor() {
        return new Refdescriptor();
    }

    /**
     * Create an instance of {@link Refname }
     * 
     */
    public Refname createRefname() {
        return new Refname();
    }

    /**
     * Create an instance of {@link Refpurpose }
     * 
     */
    public Refpurpose createRefpurpose() {
        return new Refpurpose();
    }

    /**
     * Create an instance of {@link Refsynopsisdiv }
     * 
     */
    public Refsynopsisdiv createRefsynopsisdiv() {
        return new Refsynopsisdiv();
    }

    /**
     * Create an instance of {@link Refsect2 }
     * 
     */
    public Refsect2 createRefsect2() {
        return new Refsect2();
    }

    /**
     * Create an instance of {@link Refsect3 }
     * 
     */
    public Refsect3 createRefsect3() {
        return new Refsect3();
    }

    /**
     * Create an instance of {@link Refsection }
     * 
     */
    public Refsection createRefsection() {
        return new Refsection();
    }

    /**
     * Create an instance of {@link Refsect1 }
     * 
     */
    public Refsect1 createRefsect1() {
        return new Refsect1();
    }

    /**
     * Create an instance of {@link Simplesect }
     * 
     */
    public Simplesect createSimplesect() {
        return new Simplesect();
    }

    /**
     * Create an instance of {@link Sect1 }
     * 
     */
    public Sect1 createSect1() {
        return new Sect1();
    }

    /**
     * Create an instance of {@link Sect2 }
     * 
     */
    public Sect2 createSect2() {
        return new Sect2();
    }

    /**
     * Create an instance of {@link Sect3 }
     * 
     */
    public Sect3 createSect3() {
        return new Sect3();
    }

    /**
     * Create an instance of {@link Sect4 }
     * 
     */
    public Sect4 createSect4() {
        return new Sect4();
    }

    /**
     * Create an instance of {@link Sect5 }
     * 
     */
    public Sect5 createSect5() {
        return new Sect5();
    }

    /**
     * Create an instance of {@link Dedication }
     * 
     */
    public Dedication createDedication() {
        return new Dedication();
    }

    /**
     * Create an instance of {@link Acknowledgements }
     * 
     */
    public Acknowledgements createAcknowledgements() {
        return new Acknowledgements();
    }

    /**
     * Create an instance of {@link Chapter }
     * 
     */
    public Chapter createChapter() {
        return new Chapter();
    }

    /**
     * Create an instance of {@link Set }
     * 
     */
    public Set createSet() {
        return new Set();
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

    /**
     * Create an instance of {@link Preface }
     * 
     */
    public Preface createPreface() {
        return new Preface();
    }

    /**
     * Create an instance of {@link Article }
     * 
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link Colophon }
     * 
     */
    public Colophon createColophon() {
        return new Colophon();
    }

    /**
     * Create an instance of {@link Part }
     * 
     */
    public Part createPart() {
        return new Part();
    }

    /**
     * Create an instance of {@link Partintro }
     * 
     */
    public Partintro createPartintro() {
        return new Partintro();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link Setindex }
     * 
     */
    public Setindex createSetindex() {
        return new Setindex();
    }

}
